### ISSUE TITLE
 Unreachable code

### ISSUE THREAD

**Issue by kage-sakura** [Mametaro-discord/discord-slash-commands-v12#26]
実行されないコードがあります。
https://github.com/Mametaro-discord/discord-slash-commands-v12/blob/cd968d9fabd738468de00cde7dce97e58af89a56/src/classes/ApplicationCommandPermissionsManager.js#L114-L120

**Comment by Mametaro-discord** [comment]
okサンガツ！

**Comment by kage-sakura** [comment]
resolved
