### ISSUE TITLE
Unknown code

### ISSUE THREAD

**Issue by kage-sakura** [Mametaro-discord/discord-slash-commands-v12#28]
ちょっとよくわからない()
https://github.com/Mametaro-discord/discord-slash-commands-v12/blob/cd968d9fabd738468de00cde7dce97e58af89a56/src/classes/ApplicationCommandManager.js#L110

**Comment by Mametaro-discord** [comment]
エグミスだなこれあとでなおす！

**Comment by kage-sakura** [comment]
resolved
